//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlarmWorkflow.Backend.Service.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlarmWorkflow.Backend.Service.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot install service (most likely it does already exist). The error message was: {0}.
        /// </summary>
        internal static string InstallServiceError_Message {
            get {
                return ResourceManager.GetString("InstallServiceError_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while starting the AlarmWorkflow service. The error message was: {0}.
        /// </summary>
        internal static string ServiceStartError_Message {
            get {
                return ResourceManager.GetString("ServiceStartError_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service hosted in {0} milliseconds..
        /// </summary>
        internal static string SvcMgrServiceHosted {
            get {
                return ResourceManager.GetString("SvcMgrServiceHosted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hosting service {0}....
        /// </summary>
        internal static string SvcMgrServiceHosting {
            get {
                return ResourceManager.GetString("SvcMgrServiceHosting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service failed hosting! See log for further information..
        /// </summary>
        internal static string SvcMgrServiceHostingError {
            get {
                return ResourceManager.GetString("SvcMgrServiceHostingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service does not derive from {0} as required by the service manager! Cannot host service..
        /// </summary>
        internal static string SvcMgrServiceInstanceIllegalType {
            get {
                return ResourceManager.GetString("SvcMgrServiceInstanceIllegalType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service manager started. Hosted {0} internal and {1} exposed services..
        /// </summary>
        internal static string SvcMgrStarted {
            get {
                return ResourceManager.GetString("SvcMgrStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting service manager and hosting all services....
        /// </summary>
        internal static string SvcMgrStarting {
            get {
                return ResourceManager.GetString("SvcMgrStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped service manager..
        /// </summary>
        internal static string SvcMgrStopped {
            get {
                return ResourceManager.GetString("SvcMgrStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping service manager and all services....
        /// </summary>
        internal static string SvcMgrStopping {
            get {
                return ResourceManager.GetString("SvcMgrStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot uninstall service (most likely it does not exist). The error message was: {0}.
        /// </summary>
        internal static string UnInstallServiceError_Message {
            get {
                return ResourceManager.GetString("UnInstallServiceError_Message", resourceCulture);
            }
        }
    }
}
