//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlarmWorkflow.Windows.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlarmWorkflow.Windows.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation with Id &apos;{0}&apos; was acknowledged..
        /// </summary>
        internal static string AcknowledgedOperation {
            get {
                return ResourceManager.GetString("AcknowledgedOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not set operation to &apos;acknowledged&apos;. Most likely a connection issue or internal error. See log for further information..
        /// </summary>
        internal static string AcknowledgeOperationFailed {
            get {
                return ResourceManager.GetString("AcknowledgeOperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find operation viewer with alias &apos;{0}&apos;. Using the default one. Please check the configuration!.
        /// </summary>
        internal static string DesiredOperationViewerNotFound {
            get {
                return ResourceManager.GetString("DesiredOperationViewerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eine Standardansicht für Alarme..
        /// </summary>
        internal static string ExportDowDescription {
            get {
                return ResourceManager.GetString("ExportDowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        internal static string ExportDowDisplayName {
            get {
                return ResourceManager.GetString("ExportDowDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while initializing UI-job type &apos;{0}&apos;. The error message was: {1}.
        /// </summary>
        internal static string JobGenericError {
            get {
                return ResourceManager.GetString("JobGenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing UI-job type &apos;{0}&apos;....
        /// </summary>
        internal static string JobInitializeBegin {
            get {
                return ResourceManager.GetString("JobInitializeBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI-Job type &apos;{0}&apos; initialization failed. The UI-job will not be executed..
        /// </summary>
        internal static string JobInitializeError {
            get {
                return ResourceManager.GetString("JobInitializeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI-Job type &apos;{0}&apos; initialization successful..
        /// </summary>
        internal static string JobInitializeSuccess {
            get {
                return ResourceManager.GetString("JobInitializeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kann nicht zum Server verbinden. Stellen Sie sicher, dass die Serveradresse richtig eingestellt ist und dass der Service erreichbar ist und versuchen Sie es erneut..
        /// </summary>
        internal static string UICannotStartWithoutConnectionError {
            get {
                return ResourceManager.GetString("UICannotStartWithoutConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The UI-configuration was successfully loaded..
        /// </summary>
        internal static string UIConfigurationLoaded {
            get {
                return ResourceManager.GetString("UIConfigurationLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The UI-configuration could not be loaded! Using default configuration..
        /// </summary>
        internal static string UIConfigurationLoadError {
            get {
                return ResourceManager.GetString("UIConfigurationLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wenn Sie die Anwendung schließen, kann keine Benachrichtigung auf diesem System mehr angezeigt werden! Sind Sie sicher?.
        /// </summary>
        internal static string UIServiceExitWarning {
            get {
                return ResourceManager.GetString("UIServiceExitWarning", resourceCulture);
            }
        }
    }
}
