//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlarmWorkflow.Tools.MigrateUserSettingsFile.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlarmWorkflow.Tools.MigrateUserSettingsFile.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die angeforderte Datei kann nicht gefunden werden!.
        /// </summary>
        internal static string FileDoesNotExist {
            get {
                return ResourceManager.GetString("FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Import konnte nicht erfolgreich durchgeführt werden..
        /// </summary>
        internal static string OverallImportError {
            get {
                return ResourceManager.GetString("OverallImportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Überschreibe Einstellung &apos;{0}.{1}&apos;....
        /// </summary>
        internal static string OverwritingExistingItem {
            get {
                return ResourceManager.GetString("OverwritingExistingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Vorgang ist beendet..
        /// </summary>
        internal static string ProcessFinished {
            get {
                return ResourceManager.GetString("ProcessFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist ein Fehler aufgetreten beim Schreiben der Einstellung..
        /// </summary>
        internal static string SettingWriteError {
            get {
                return ResourceManager.GetString("SettingWriteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellung &apos;{0}.{1}&apos; wurde geschrieben..
        /// </summary>
        internal static string SettingWritten {
            get {
                return ResourceManager.GetString("SettingWritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema attributeFormDefault=&quot;unqualified&quot; elementFormDefault=&quot;qualified&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;xs:element name=&quot;UserSettings&quot;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:sequence&gt;
        ///        &lt;xs:element maxOccurs=&quot;unbounded&quot; name=&quot;Section&quot;&gt;
        ///          &lt;xs:complexType&gt;
        ///            &lt;xs:sequence&gt;
        ///              &lt;xs:element maxOccurs=&quot;unbounded&quot; name=&quot;UserSetting&quot;&gt;
        ///                &lt;xs:complexType&gt;
        ///                  &lt;xs:simpleContent&gt;
        ///                [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UserSettingsSchema {
            get {
                return ResourceManager.GetString("UserSettingsSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Datei &apos;user.settings&apos; weist eine falsche Formatierung auf und kann nicht importiert werden!.
        /// </summary>
        internal static string UserSettingsSchemaValidationFailure {
            get {
                return ResourceManager.GetString("UserSettingsSchemaValidationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Willkommen! Bitte geben Sie den Pfad zu Ihrer user.settings-Datei ein, oder drücken Sie [Return], um die Datei von ihrem Standardpfad zu importieren.
        ///
        ///Beachten Sie: Bereits existierende Einstellungen werden in der Datenbank überschrieben!.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
