//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("AlarmWorkflowModel", "FK_User_AccessRight_AccessRight_Id", "accessright", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AlarmWorkflow.Job.MySqlDatabaseJob.Data.AccessRight), "user_accessright", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AlarmWorkflow.Job.MySqlDatabaseJob.Data.User_AccessRight), true)]
[assembly: EdmRelationshipAttribute("AlarmWorkflowModel", "FK_Address_Person_Id", "person", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AlarmWorkflow.Job.MySqlDatabaseJob.Data.PersonData), "address", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AlarmWorkflow.Job.MySqlDatabaseJob.Data.AddressData), true)]
[assembly: EdmRelationshipAttribute("AlarmWorkflowModel", "FK_User_Person_Id", "person", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(AlarmWorkflow.Job.MySqlDatabaseJob.Data.PersonData), "user", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AlarmWorkflow.Job.MySqlDatabaseJob.Data.UserData), true)]
[assembly: EdmRelationshipAttribute("AlarmWorkflowModel", "FK_User_AccessRight_User_Id", "user", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AlarmWorkflow.Job.MySqlDatabaseJob.Data.UserData), "user_accessright", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AlarmWorkflow.Job.MySqlDatabaseJob.Data.User_AccessRight), true)]

#endregion

namespace AlarmWorkflow.Job.MySqlDatabaseJob.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AlarmWorkflowEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AlarmWorkflowEntities object using the connection string found in the 'AlarmWorkflowEntities' section of the application configuration file.
        /// </summary>
        public AlarmWorkflowEntities() : base("name=AlarmWorkflowEntities", "AlarmWorkflowEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AlarmWorkflowEntities object.
        /// </summary>
        public AlarmWorkflowEntities(string connectionString) : base(connectionString, "AlarmWorkflowEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AlarmWorkflowEntities object.
        /// </summary>
        public AlarmWorkflowEntities(EntityConnection connection) : base(connection, "AlarmWorkflowEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AccessRight> AccessRights
        {
            get
            {
                if ((_AccessRights == null))
                {
                    _AccessRights = base.CreateObjectSet<AccessRight>("AccessRights");
                }
                return _AccessRights;
            }
        }
        private ObjectSet<AccessRight> _AccessRights;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AddressData> Addresses
        {
            get
            {
                if ((_Addresses == null))
                {
                    _Addresses = base.CreateObjectSet<AddressData>("Addresses");
                }
                return _Addresses;
            }
        }
        private ObjectSet<AddressData> _Addresses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<OperationData> Operations
        {
            get
            {
                if ((_Operations == null))
                {
                    _Operations = base.CreateObjectSet<OperationData>("Operations");
                }
                return _Operations;
            }
        }
        private ObjectSet<OperationData> _Operations;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PersonData> People
        {
            get
            {
                if ((_People == null))
                {
                    _People = base.CreateObjectSet<PersonData>("People");
                }
                return _People;
            }
        }
        private ObjectSet<PersonData> _People;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tb_einsatz> tb_einsatz
        {
            get
            {
                if ((_tb_einsatz == null))
                {
                    _tb_einsatz = base.CreateObjectSet<tb_einsatz>("tb_einsatz");
                }
                return _tb_einsatz;
            }
        }
        private ObjectSet<tb_einsatz> _tb_einsatz;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UserData> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<UserData>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<UserData> _Users;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User_AccessRight> User_AccessRight
        {
            get
            {
                if ((_User_AccessRight == null))
                {
                    _User_AccessRight = base.CreateObjectSet<User_AccessRight>("User_AccessRight");
                }
                return _User_AccessRight;
            }
        }
        private ObjectSet<User_AccessRight> _User_AccessRight;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AccessRights EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAccessRights(AccessRight accessRight)
        {
            base.AddObject("AccessRights", accessRight);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Addresses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAddresses(AddressData addressData)
        {
            base.AddObject("Addresses", addressData);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Operations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOperations(OperationData operationData)
        {
            base.AddObject("Operations", operationData);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the People EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPeople(PersonData personData)
        {
            base.AddObject("People", personData);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tb_einsatz EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotb_einsatz(tb_einsatz tb_einsatz)
        {
            base.AddObject("tb_einsatz", tb_einsatz);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(UserData userData)
        {
            base.AddObject("Users", userData);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the User_AccessRight EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUser_AccessRight(User_AccessRight user_AccessRight)
        {
            base.AddObject("User_AccessRight", user_AccessRight);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AlarmWorkflowModel", Name="AccessRight")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AccessRight : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AccessRight object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static AccessRight CreateAccessRight(global::System.Int32 id, global::System.String name)
        {
            AccessRight accessRight = new AccessRight();
            accessRight.Id = id;
            accessRight.Name = name;
            return accessRight;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AlarmWorkflowModel", "FK_User_AccessRight_AccessRight_Id", "user_accessright")]
        public EntityCollection<User_AccessRight> user_accessright
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<User_AccessRight>("AlarmWorkflowModel.FK_User_AccessRight_AccessRight_Id", "user_accessright");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<User_AccessRight>("AlarmWorkflowModel.FK_User_AccessRight_AccessRight_Id", "user_accessright", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AlarmWorkflowModel", Name="AddressData")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AddressData : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AddressData object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="person_Id">Initial value of the Person_Id property.</param>
        /// <param name="addressType">Initial value of the AddressType property.</param>
        public static AddressData CreateAddressData(global::System.Int32 id, global::System.Int32 person_Id, global::System.String addressType)
        {
            AddressData addressData = new AddressData();
            addressData.Id = id;
            addressData.Person_Id = person_Id;
            addressData.AddressType = addressType;
            return addressData;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Person_Id
        {
            get
            {
                return _Person_Id;
            }
            set
            {
                OnPerson_IdChanging(value);
                ReportPropertyChanging("Person_Id");
                _Person_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Person_Id");
                OnPerson_IdChanged();
            }
        }
        private global::System.Int32 _Person_Id;
        partial void OnPerson_IdChanging(global::System.Int32 value);
        partial void OnPerson_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AddressType
        {
            get
            {
                return _AddressType;
            }
            set
            {
                OnAddressTypeChanging(value);
                ReportPropertyChanging("AddressType");
                _AddressType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AddressType");
                OnAddressTypeChanged();
            }
        }
        private global::System.String _AddressType;
        partial void OnAddressTypeChanging(global::System.String value);
        partial void OnAddressTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AddressValue
        {
            get
            {
                return _AddressValue;
            }
            set
            {
                OnAddressValueChanging(value);
                ReportPropertyChanging("AddressValue");
                _AddressValue = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AddressValue");
                OnAddressValueChanged();
            }
        }
        private global::System.String _AddressValue;
        partial void OnAddressValueChanging(global::System.String value);
        partial void OnAddressValueChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AlarmWorkflowModel", "FK_Address_Person_Id", "person")]
        public PersonData person
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PersonData>("AlarmWorkflowModel.FK_Address_Person_Id", "person").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PersonData>("AlarmWorkflowModel.FK_Address_Person_Id", "person").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PersonData> personReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PersonData>("AlarmWorkflowModel.FK_Address_Person_Id", "person");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PersonData>("AlarmWorkflowModel.FK_Address_Person_Id", "person", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AlarmWorkflowModel", Name="OperationData")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class OperationData : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new OperationData object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="isAcknowledged">Initial value of the IsAcknowledged property.</param>
        /// <param name="timestamp">Initial value of the Timestamp property.</param>
        /// <param name="operationId">Initial value of the OperationId property.</param>
        /// <param name="serialized">Initial value of the Serialized property.</param>
        public static OperationData CreateOperationData(global::System.Int32 id, global::System.Boolean isAcknowledged, global::System.DateTime timestamp, global::System.Guid operationId, global::System.Byte[] serialized)
        {
            OperationData operationData = new OperationData();
            operationData.Id = id;
            operationData.IsAcknowledged = isAcknowledged;
            operationData.Timestamp = timestamp;
            operationData.OperationId = operationId;
            operationData.Serialized = serialized;
            return operationData;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsAcknowledged
        {
            get
            {
                return _IsAcknowledged;
            }
            set
            {
                OnIsAcknowledgedChanging(value);
                ReportPropertyChanging("IsAcknowledged");
                _IsAcknowledged = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsAcknowledged");
                OnIsAcknowledgedChanged();
            }
        }
        private global::System.Boolean _IsAcknowledged;
        partial void OnIsAcknowledgedChanging(global::System.Boolean value);
        partial void OnIsAcknowledgedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Timestamp
        {
            get
            {
                return _Timestamp;
            }
            set
            {
                OnTimestampChanging(value);
                ReportPropertyChanging("Timestamp");
                _Timestamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Timestamp");
                OnTimestampChanged();
            }
        }
        private global::System.DateTime _Timestamp;
        partial void OnTimestampChanging(global::System.DateTime value);
        partial void OnTimestampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid OperationId
        {
            get
            {
                return _OperationId;
            }
            set
            {
                OnOperationIdChanging(value);
                ReportPropertyChanging("OperationId");
                _OperationId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OperationId");
                OnOperationIdChanged();
            }
        }
        private global::System.Guid _OperationId;
        partial void OnOperationIdChanging(global::System.Guid value);
        partial void OnOperationIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] Serialized
        {
            get
            {
                return StructuralObject.GetValidValue(_Serialized);
            }
            set
            {
                OnSerializedChanging(value);
                ReportPropertyChanging("Serialized");
                _Serialized = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Serialized");
                OnSerializedChanged();
            }
        }
        private global::System.Byte[] _Serialized;
        partial void OnSerializedChanging(global::System.Byte[] value);
        partial void OnSerializedChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AlarmWorkflowModel", Name="PersonData")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PersonData : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PersonData object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        /// <param name="lastName">Initial value of the LastName property.</param>
        public static PersonData CreatePersonData(global::System.Int32 id, global::System.String firstName, global::System.String lastName)
        {
            PersonData personData = new PersonData();
            personData.Id = id;
            personData.FirstName = firstName;
            personData.LastName = lastName;
            return personData;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AlarmWorkflowModel", "FK_Address_Person_Id", "address")]
        public EntityCollection<AddressData> addresses
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<AddressData>("AlarmWorkflowModel.FK_Address_Person_Id", "address");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<AddressData>("AlarmWorkflowModel.FK_Address_Person_Id", "address", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AlarmWorkflowModel", "FK_User_Person_Id", "user")]
        public EntityCollection<UserData> users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UserData>("AlarmWorkflowModel.FK_User_Person_Id", "user");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UserData>("AlarmWorkflowModel.FK_User_Person_Id", "user", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Legacy table from old AlarmWorkflow; still in use.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AlarmWorkflowModel", Name="tb_einsatz")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_einsatz : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tb_einsatz object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static tb_einsatz Createtb_einsatz(global::System.Int32 id)
        {
            tb_einsatz tb_einsatz = new tb_einsatz();
            tb_einsatz.id = id;
            return tb_einsatz;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Einsatznr
        {
            get
            {
                return _Einsatznr;
            }
            set
            {
                OnEinsatznrChanging(value);
                ReportPropertyChanging("Einsatznr");
                _Einsatznr = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Einsatznr");
                OnEinsatznrChanged();
            }
        }
        private global::System.String _Einsatznr;
        partial void OnEinsatznrChanging(global::System.String value);
        partial void OnEinsatznrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Einsatzort
        {
            get
            {
                return _Einsatzort;
            }
            set
            {
                OnEinsatzortChanging(value);
                ReportPropertyChanging("Einsatzort");
                _Einsatzort = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Einsatzort");
                OnEinsatzortChanged();
            }
        }
        private global::System.String _Einsatzort;
        partial void OnEinsatzortChanging(global::System.String value);
        partial void OnEinsatzortChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Einsatzplan
        {
            get
            {
                return _Einsatzplan;
            }
            set
            {
                OnEinsatzplanChanging(value);
                ReportPropertyChanging("Einsatzplan");
                _Einsatzplan = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Einsatzplan");
                OnEinsatzplanChanged();
            }
        }
        private global::System.String _Einsatzplan;
        partial void OnEinsatzplanChanging(global::System.String value);
        partial void OnEinsatzplanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Hinweis
        {
            get
            {
                return _Hinweis;
            }
            set
            {
                OnHinweisChanging(value);
                ReportPropertyChanging("Hinweis");
                _Hinweis = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Hinweis");
                OnHinweisChanged();
            }
        }
        private global::System.String _Hinweis;
        partial void OnHinweisChanging(global::System.String value);
        partial void OnHinweisChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Kreuzung
        {
            get
            {
                return _Kreuzung;
            }
            set
            {
                OnKreuzungChanging(value);
                ReportPropertyChanging("Kreuzung");
                _Kreuzung = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Kreuzung");
                OnKreuzungChanged();
            }
        }
        private global::System.String _Kreuzung;
        partial void OnKreuzungChanging(global::System.String value);
        partial void OnKreuzungChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Meldebild
        {
            get
            {
                return _Meldebild;
            }
            set
            {
                OnMeldebildChanging(value);
                ReportPropertyChanging("Meldebild");
                _Meldebild = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Meldebild");
                OnMeldebildChanged();
            }
        }
        private global::System.String _Meldebild;
        partial void OnMeldebildChanging(global::System.String value);
        partial void OnMeldebildChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Mitteiler
        {
            get
            {
                return _Mitteiler;
            }
            set
            {
                OnMitteilerChanging(value);
                ReportPropertyChanging("Mitteiler");
                _Mitteiler = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Mitteiler");
                OnMitteilerChanged();
            }
        }
        private global::System.String _Mitteiler;
        partial void OnMitteilerChanging(global::System.String value);
        partial void OnMitteilerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Objekt
        {
            get
            {
                return _Objekt;
            }
            set
            {
                OnObjektChanging(value);
                ReportPropertyChanging("Objekt");
                _Objekt = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Objekt");
                OnObjektChanged();
            }
        }
        private global::System.String _Objekt;
        partial void OnObjektChanging(global::System.String value);
        partial void OnObjektChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ort
        {
            get
            {
                return _Ort;
            }
            set
            {
                OnOrtChanging(value);
                ReportPropertyChanging("Ort");
                _Ort = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ort");
                OnOrtChanged();
            }
        }
        private global::System.String _Ort;
        partial void OnOrtChanging(global::System.String value);
        partial void OnOrtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Strasse
        {
            get
            {
                return _Strasse;
            }
            set
            {
                OnStrasseChanging(value);
                ReportPropertyChanging("Strasse");
                _Strasse = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Strasse");
                OnStrasseChanged();
            }
        }
        private global::System.String _Strasse;
        partial void OnStrasseChanging(global::System.String value);
        partial void OnStrasseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Fahrzeuge
        {
            get
            {
                return _Fahrzeuge;
            }
            set
            {
                OnFahrzeugeChanging(value);
                ReportPropertyChanging("Fahrzeuge");
                _Fahrzeuge = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Fahrzeuge");
                OnFahrzeugeChanged();
            }
        }
        private global::System.String _Fahrzeuge;
        partial void OnFahrzeugeChanging(global::System.String value);
        partial void OnFahrzeugeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Einsatzstichwort
        {
            get
            {
                return _Einsatzstichwort;
            }
            set
            {
                OnEinsatzstichwortChanging(value);
                ReportPropertyChanging("Einsatzstichwort");
                _Einsatzstichwort = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Einsatzstichwort");
                OnEinsatzstichwortChanged();
            }
        }
        private global::System.String _Einsatzstichwort;
        partial void OnEinsatzstichwortChanging(global::System.String value);
        partial void OnEinsatzstichwortChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Alarmtime
        {
            get
            {
                return _Alarmtime;
            }
            set
            {
                OnAlarmtimeChanging(value);
                ReportPropertyChanging("Alarmtime");
                _Alarmtime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Alarmtime");
                OnAlarmtimeChanged();
            }
        }
        private global::System.String _Alarmtime;
        partial void OnAlarmtimeChanging(global::System.String value);
        partial void OnAlarmtimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Faxtime
        {
            get
            {
                return _Faxtime;
            }
            set
            {
                OnFaxtimeChanging(value);
                ReportPropertyChanging("Faxtime");
                _Faxtime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Faxtime");
                OnFaxtimeChanged();
            }
        }
        private global::System.String _Faxtime;
        partial void OnFaxtimeChanging(global::System.String value);
        partial void OnFaxtimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Stichwort
        {
            get
            {
                return _Stichwort;
            }
            set
            {
                OnStichwortChanging(value);
                ReportPropertyChanging("Stichwort");
                _Stichwort = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Stichwort");
                OnStichwortChanged();
            }
        }
        private global::System.String _Stichwort;
        partial void OnStichwortChanging(global::System.String value);
        partial void OnStichwortChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AlarmWorkflowModel", Name="User_AccessRight")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User_AccessRight : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User_AccessRight object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="user_Id">Initial value of the User_Id property.</param>
        /// <param name="accessRight_Id">Initial value of the AccessRight_Id property.</param>
        public static User_AccessRight CreateUser_AccessRight(global::System.Int32 id, global::System.Int32 user_Id, global::System.Int32 accessRight_Id)
        {
            User_AccessRight user_AccessRight = new User_AccessRight();
            user_AccessRight.Id = id;
            user_AccessRight.User_Id = user_Id;
            user_AccessRight.AccessRight_Id = accessRight_Id;
            return user_AccessRight;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 User_Id
        {
            get
            {
                return _User_Id;
            }
            set
            {
                OnUser_IdChanging(value);
                ReportPropertyChanging("User_Id");
                _User_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("User_Id");
                OnUser_IdChanged();
            }
        }
        private global::System.Int32 _User_Id;
        partial void OnUser_IdChanging(global::System.Int32 value);
        partial void OnUser_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AccessRight_Id
        {
            get
            {
                return _AccessRight_Id;
            }
            set
            {
                OnAccessRight_IdChanging(value);
                ReportPropertyChanging("AccessRight_Id");
                _AccessRight_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AccessRight_Id");
                OnAccessRight_IdChanged();
            }
        }
        private global::System.Int32 _AccessRight_Id;
        partial void OnAccessRight_IdChanging(global::System.Int32 value);
        partial void OnAccessRight_IdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AlarmWorkflowModel", "FK_User_AccessRight_AccessRight_Id", "accessright")]
        public AccessRight accessright
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AccessRight>("AlarmWorkflowModel.FK_User_AccessRight_AccessRight_Id", "accessright").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AccessRight>("AlarmWorkflowModel.FK_User_AccessRight_AccessRight_Id", "accessright").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<AccessRight> accessrightReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AccessRight>("AlarmWorkflowModel.FK_User_AccessRight_AccessRight_Id", "accessright");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<AccessRight>("AlarmWorkflowModel.FK_User_AccessRight_AccessRight_Id", "accessright", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AlarmWorkflowModel", "FK_User_AccessRight_User_Id", "user")]
        public UserData user
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserData>("AlarmWorkflowModel.FK_User_AccessRight_User_Id", "user").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserData>("AlarmWorkflowModel.FK_User_AccessRight_User_Id", "user").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<UserData> userReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserData>("AlarmWorkflowModel.FK_User_AccessRight_User_Id", "user");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<UserData>("AlarmWorkflowModel.FK_User_AccessRight_User_Id", "user", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AlarmWorkflowModel", Name="UserData")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserData : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UserData object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static UserData CreateUserData(global::System.Int32 id, global::System.String name)
        {
            UserData userData = new UserData();
            userData.Id = id;
            userData.Name = name;
            return userData;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Person_Id
        {
            get
            {
                return _Person_Id;
            }
            set
            {
                OnPerson_IdChanging(value);
                ReportPropertyChanging("Person_Id");
                _Person_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Person_Id");
                OnPerson_IdChanged();
            }
        }
        private Nullable<global::System.Int32> _Person_Id;
        partial void OnPerson_IdChanging(Nullable<global::System.Int32> value);
        partial void OnPerson_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Password
        {
            get
            {
                return StructuralObject.GetValidValue(_Password);
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.Byte[] _Password;
        partial void OnPasswordChanging(global::System.Byte[] value);
        partial void OnPasswordChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AlarmWorkflowModel", "FK_User_Person_Id", "person")]
        public PersonData person
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PersonData>("AlarmWorkflowModel.FK_User_Person_Id", "person").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PersonData>("AlarmWorkflowModel.FK_User_Person_Id", "person").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PersonData> personReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PersonData>("AlarmWorkflowModel.FK_User_Person_Id", "person");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PersonData>("AlarmWorkflowModel.FK_User_Person_Id", "person", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AlarmWorkflowModel", "FK_User_AccessRight_User_Id", "user_accessright")]
        public EntityCollection<User_AccessRight> user_accessright
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<User_AccessRight>("AlarmWorkflowModel.FK_User_AccessRight_User_Id", "user_accessright");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<User_AccessRight>("AlarmWorkflowModel.FK_User_AccessRight_User_Id", "user_accessright", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
