//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("AlarmWorkflowModel", "operationresource_ibfk_1", "OperationData", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AlarmWorkflow.BackendService.Management.Data.OperationData), "operationresource", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AlarmWorkflow.BackendService.Management.Data.OperationResourceData), true)]

#endregion

namespace AlarmWorkflow.BackendService.Management.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class OperationManagementEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new OperationManagementEntities object using the connection string found in the 'OperationManagementEntities' section of the application configuration file.
        /// </summary>
        public OperationManagementEntities() : base("name=OperationManagementEntities", "OperationManagementEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new OperationManagementEntities object.
        /// </summary>
        public OperationManagementEntities(string connectionString) : base(connectionString, "OperationManagementEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new OperationManagementEntities object.
        /// </summary>
        public OperationManagementEntities(EntityConnection connection) : base(connection, "OperationManagementEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<OperationData> Operations
        {
            get
            {
                if ((_Operations == null))
                {
                    _Operations = base.CreateObjectSet<OperationData>("Operations");
                }
                return _Operations;
            }
        }
        private ObjectSet<OperationData> _Operations;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<OperationResourceData> OperationResources
        {
            get
            {
                if ((_OperationResources == null))
                {
                    _OperationResources = base.CreateObjectSet<OperationResourceData>("OperationResources");
                }
                return _OperationResources;
            }
        }
        private ObjectSet<OperationResourceData> _OperationResources;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Operations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOperations(OperationData operationData)
        {
            base.AddObject("Operations", operationData);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the OperationResources EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOperationResources(OperationResourceData operationResourceData)
        {
            base.AddObject("OperationResources", operationResourceData);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AlarmWorkflowModel", Name="OperationData")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class OperationData : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new OperationData object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="isAcknowledged">Initial value of the IsAcknowledged property.</param>
        /// <param name="timestampIncome">Initial value of the TimestampIncome property.</param>
        /// <param name="timestampAlarm">Initial value of the TimestampAlarm property.</param>
        /// <param name="operationGuid">Initial value of the OperationGuid property.</param>
        public static OperationData CreateOperationData(global::System.Int32 id, global::System.Boolean isAcknowledged, global::System.DateTime timestampIncome, global::System.DateTime timestampAlarm, global::System.Guid operationGuid)
        {
            OperationData operationData = new OperationData();
            operationData.Id = id;
            operationData.IsAcknowledged = isAcknowledged;
            operationData.TimestampIncome = timestampIncome;
            operationData.TimestampAlarm = timestampAlarm;
            operationData.OperationGuid = operationGuid;
            return operationData;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsAcknowledged
        {
            get
            {
                return _IsAcknowledged;
            }
            set
            {
                OnIsAcknowledgedChanging(value);
                ReportPropertyChanging("IsAcknowledged");
                _IsAcknowledged = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsAcknowledged");
                OnIsAcknowledgedChanged();
            }
        }
        private global::System.Boolean _IsAcknowledged;
        partial void OnIsAcknowledgedChanging(global::System.Boolean value);
        partial void OnIsAcknowledgedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime TimestampIncome
        {
            get
            {
                return _TimestampIncome;
            }
            set
            {
                OnTimestampIncomeChanging(value);
                ReportPropertyChanging("TimestampIncome");
                _TimestampIncome = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimestampIncome");
                OnTimestampIncomeChanged();
            }
        }
        private global::System.DateTime _TimestampIncome;
        partial void OnTimestampIncomeChanging(global::System.DateTime value);
        partial void OnTimestampIncomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime TimestampAlarm
        {
            get
            {
                return _TimestampAlarm;
            }
            set
            {
                OnTimestampAlarmChanging(value);
                ReportPropertyChanging("TimestampAlarm");
                _TimestampAlarm = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimestampAlarm");
                OnTimestampAlarmChanged();
            }
        }
        private global::System.DateTime _TimestampAlarm;
        partial void OnTimestampAlarmChanging(global::System.DateTime value);
        partial void OnTimestampAlarmChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Messenger
        {
            get
            {
                return _Messenger;
            }
            set
            {
                OnMessengerChanging(value);
                ReportPropertyChanging("Messenger");
                _Messenger = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Messenger");
                OnMessengerChanged();
            }
        }
        private global::System.String _Messenger;
        partial void OnMessengerChanging(global::System.String value);
        partial void OnMessengerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comment
        {
            get
            {
                return _Comment;
            }
            set
            {
                OnCommentChanging(value);
                ReportPropertyChanging("Comment");
                _Comment = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comment");
                OnCommentChanged();
            }
        }
        private global::System.String _Comment;
        partial void OnCommentChanging(global::System.String value);
        partial void OnCommentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Plan
        {
            get
            {
                return _Plan;
            }
            set
            {
                OnPlanChanging(value);
                ReportPropertyChanging("Plan");
                _Plan = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Plan");
                OnPlanChanged();
            }
        }
        private global::System.String _Plan;
        partial void OnPlanChanging(global::System.String value);
        partial void OnPlanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Picture
        {
            get
            {
                return _Picture;
            }
            set
            {
                OnPictureChanging(value);
                ReportPropertyChanging("Picture");
                _Picture = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Picture");
                OnPictureChanged();
            }
        }
        private global::System.String _Picture;
        partial void OnPictureChanging(global::System.String value);
        partial void OnPictureChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Priority
        {
            get
            {
                return _Priority;
            }
            set
            {
                OnPriorityChanging(value);
                ReportPropertyChanging("Priority");
                _Priority = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Priority");
                OnPriorityChanged();
            }
        }
        private global::System.String _Priority;
        partial void OnPriorityChanging(global::System.String value);
        partial void OnPriorityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EinsatzortStreet
        {
            get
            {
                return _EinsatzortStreet;
            }
            set
            {
                OnEinsatzortStreetChanging(value);
                ReportPropertyChanging("EinsatzortStreet");
                _EinsatzortStreet = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EinsatzortStreet");
                OnEinsatzortStreetChanged();
            }
        }
        private global::System.String _EinsatzortStreet;
        partial void OnEinsatzortStreetChanging(global::System.String value);
        partial void OnEinsatzortStreetChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EinsatzortStreetNumber
        {
            get
            {
                return _EinsatzortStreetNumber;
            }
            set
            {
                OnEinsatzortStreetNumberChanging(value);
                ReportPropertyChanging("EinsatzortStreetNumber");
                _EinsatzortStreetNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EinsatzortStreetNumber");
                OnEinsatzortStreetNumberChanged();
            }
        }
        private global::System.String _EinsatzortStreetNumber;
        partial void OnEinsatzortStreetNumberChanging(global::System.String value);
        partial void OnEinsatzortStreetNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EinsatzortZipCode
        {
            get
            {
                return _EinsatzortZipCode;
            }
            set
            {
                OnEinsatzortZipCodeChanging(value);
                ReportPropertyChanging("EinsatzortZipCode");
                _EinsatzortZipCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EinsatzortZipCode");
                OnEinsatzortZipCodeChanged();
            }
        }
        private global::System.String _EinsatzortZipCode;
        partial void OnEinsatzortZipCodeChanging(global::System.String value);
        partial void OnEinsatzortZipCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EinsatzortCity
        {
            get
            {
                return _EinsatzortCity;
            }
            set
            {
                OnEinsatzortCityChanging(value);
                ReportPropertyChanging("EinsatzortCity");
                _EinsatzortCity = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EinsatzortCity");
                OnEinsatzortCityChanged();
            }
        }
        private global::System.String _EinsatzortCity;
        partial void OnEinsatzortCityChanging(global::System.String value);
        partial void OnEinsatzortCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EinsatzortLocation
        {
            get
            {
                return _EinsatzortLocation;
            }
            set
            {
                OnEinsatzortLocationChanging(value);
                ReportPropertyChanging("EinsatzortLocation");
                _EinsatzortLocation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EinsatzortLocation");
                OnEinsatzortLocationChanged();
            }
        }
        private global::System.String _EinsatzortLocation;
        partial void OnEinsatzortLocationChanging(global::System.String value);
        partial void OnEinsatzortLocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EinsatzortProperty
        {
            get
            {
                return _EinsatzortProperty;
            }
            set
            {
                OnEinsatzortPropertyChanging(value);
                ReportPropertyChanging("EinsatzortProperty");
                _EinsatzortProperty = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EinsatzortProperty");
                OnEinsatzortPropertyChanged();
            }
        }
        private global::System.String _EinsatzortProperty;
        partial void OnEinsatzortPropertyChanging(global::System.String value);
        partial void OnEinsatzortPropertyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EinsatzortLatLng
        {
            get
            {
                return _EinsatzortLatLng;
            }
            set
            {
                OnEinsatzortLatLngChanging(value);
                ReportPropertyChanging("EinsatzortLatLng");
                _EinsatzortLatLng = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EinsatzortLatLng");
                OnEinsatzortLatLngChanged();
            }
        }
        private global::System.String _EinsatzortLatLng;
        partial void OnEinsatzortLatLngChanging(global::System.String value);
        partial void OnEinsatzortLatLngChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ZielortStreet
        {
            get
            {
                return _ZielortStreet;
            }
            set
            {
                OnZielortStreetChanging(value);
                ReportPropertyChanging("ZielortStreet");
                _ZielortStreet = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ZielortStreet");
                OnZielortStreetChanged();
            }
        }
        private global::System.String _ZielortStreet;
        partial void OnZielortStreetChanging(global::System.String value);
        partial void OnZielortStreetChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ZielortStreetNumber
        {
            get
            {
                return _ZielortStreetNumber;
            }
            set
            {
                OnZielortStreetNumberChanging(value);
                ReportPropertyChanging("ZielortStreetNumber");
                _ZielortStreetNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ZielortStreetNumber");
                OnZielortStreetNumberChanged();
            }
        }
        private global::System.String _ZielortStreetNumber;
        partial void OnZielortStreetNumberChanging(global::System.String value);
        partial void OnZielortStreetNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ZielortZipCode
        {
            get
            {
                return _ZielortZipCode;
            }
            set
            {
                OnZielortZipCodeChanging(value);
                ReportPropertyChanging("ZielortZipCode");
                _ZielortZipCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ZielortZipCode");
                OnZielortZipCodeChanged();
            }
        }
        private global::System.String _ZielortZipCode;
        partial void OnZielortZipCodeChanging(global::System.String value);
        partial void OnZielortZipCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ZielortCity
        {
            get
            {
                return _ZielortCity;
            }
            set
            {
                OnZielortCityChanging(value);
                ReportPropertyChanging("ZielortCity");
                _ZielortCity = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ZielortCity");
                OnZielortCityChanged();
            }
        }
        private global::System.String _ZielortCity;
        partial void OnZielortCityChanging(global::System.String value);
        partial void OnZielortCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ZielortLocation
        {
            get
            {
                return _ZielortLocation;
            }
            set
            {
                OnZielortLocationChanging(value);
                ReportPropertyChanging("ZielortLocation");
                _ZielortLocation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ZielortLocation");
                OnZielortLocationChanged();
            }
        }
        private global::System.String _ZielortLocation;
        partial void OnZielortLocationChanging(global::System.String value);
        partial void OnZielortLocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ZielortProperty
        {
            get
            {
                return _ZielortProperty;
            }
            set
            {
                OnZielortPropertyChanging(value);
                ReportPropertyChanging("ZielortProperty");
                _ZielortProperty = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ZielortProperty");
                OnZielortPropertyChanged();
            }
        }
        private global::System.String _ZielortProperty;
        partial void OnZielortPropertyChanging(global::System.String value);
        partial void OnZielortPropertyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ZielortLatLng
        {
            get
            {
                return _ZielortLatLng;
            }
            set
            {
                OnZielortLatLngChanging(value);
                ReportPropertyChanging("ZielortLatLng");
                _ZielortLatLng = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ZielortLatLng");
                OnZielortLatLngChanged();
            }
        }
        private global::System.String _ZielortLatLng;
        partial void OnZielortLatLngChanging(global::System.String value);
        partial void OnZielortLatLngChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LoopsCsv
        {
            get
            {
                return _LoopsCsv;
            }
            set
            {
                OnLoopsCsvChanging(value);
                ReportPropertyChanging("LoopsCsv");
                _LoopsCsv = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LoopsCsv");
                OnLoopsCsvChanged();
            }
        }
        private global::System.String _LoopsCsv;
        partial void OnLoopsCsvChanging(global::System.String value);
        partial void OnLoopsCsvChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CustomDataJson
        {
            get
            {
                return _CustomDataJson;
            }
            set
            {
                OnCustomDataJsonChanging(value);
                ReportPropertyChanging("CustomDataJson");
                _CustomDataJson = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CustomDataJson");
                OnCustomDataJsonChanged();
            }
        }
        private global::System.String _CustomDataJson;
        partial void OnCustomDataJsonChanging(global::System.String value);
        partial void OnCustomDataJsonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OperationNumber
        {
            get
            {
                return _OperationNumber;
            }
            set
            {
                OnOperationNumberChanging(value);
                ReportPropertyChanging("OperationNumber");
                _OperationNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OperationNumber");
                OnOperationNumberChanged();
            }
        }
        private global::System.String _OperationNumber;
        partial void OnOperationNumberChanging(global::System.String value);
        partial void OnOperationNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid OperationGuid
        {
            get
            {
                return _OperationGuid;
            }
            set
            {
                OnOperationGuidChanging(value);
                ReportPropertyChanging("OperationGuid");
                _OperationGuid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OperationGuid");
                OnOperationGuidChanged();
            }
        }
        private global::System.Guid _OperationGuid;
        partial void OnOperationGuidChanging(global::System.Guid value);
        partial void OnOperationGuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EinsatzortIntersection
        {
            get
            {
                return _EinsatzortIntersection;
            }
            set
            {
                OnEinsatzortIntersectionChanging(value);
                ReportPropertyChanging("EinsatzortIntersection");
                _EinsatzortIntersection = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EinsatzortIntersection");
                OnEinsatzortIntersectionChanged();
            }
        }
        private global::System.String _EinsatzortIntersection;
        partial void OnEinsatzortIntersectionChanging(global::System.String value);
        partial void OnEinsatzortIntersectionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ZielortIntersection
        {
            get
            {
                return _ZielortIntersection;
            }
            set
            {
                OnZielortIntersectionChanging(value);
                ReportPropertyChanging("ZielortIntersection");
                _ZielortIntersection = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ZielortIntersection");
                OnZielortIntersectionChanged();
            }
        }
        private global::System.String _ZielortIntersection;
        partial void OnZielortIntersectionChanging(global::System.String value);
        partial void OnZielortIntersectionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Keyword
        {
            get
            {
                return _Keyword;
            }
            set
            {
                OnKeywordChanging(value);
                ReportPropertyChanging("Keyword");
                _Keyword = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Keyword");
                OnKeywordChanged();
            }
        }
        private global::System.String _Keyword;
        partial void OnKeywordChanging(global::System.String value);
        partial void OnKeywordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String KeywordB
        {
            get
            {
                return _KeywordB;
            }
            set
            {
                OnKeywordBChanging(value);
                ReportPropertyChanging("KeywordB");
                _KeywordB = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("KeywordB");
                OnKeywordBChanged();
            }
        }
        private global::System.String _KeywordB;
        partial void OnKeywordBChanging(global::System.String value);
        partial void OnKeywordBChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String KeywordR
        {
            get
            {
                return _KeywordR;
            }
            set
            {
                OnKeywordRChanging(value);
                ReportPropertyChanging("KeywordR");
                _KeywordR = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("KeywordR");
                OnKeywordRChanged();
            }
        }
        private global::System.String _KeywordR;
        partial void OnKeywordRChanging(global::System.String value);
        partial void OnKeywordRChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String KeywordS
        {
            get
            {
                return _KeywordS;
            }
            set
            {
                OnKeywordSChanging(value);
                ReportPropertyChanging("KeywordS");
                _KeywordS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("KeywordS");
                OnKeywordSChanged();
            }
        }
        private global::System.String _KeywordS;
        partial void OnKeywordSChanging(global::System.String value);
        partial void OnKeywordSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String KeywordT
        {
            get
            {
                return _KeywordT;
            }
            set
            {
                OnKeywordTChanging(value);
                ReportPropertyChanging("KeywordT");
                _KeywordT = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("KeywordT");
                OnKeywordTChanged();
            }
        }
        private global::System.String _KeywordT;
        partial void OnKeywordTChanging(global::System.String value);
        partial void OnKeywordTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String KeywordMisc
        {
            get
            {
                return _KeywordMisc;
            }
            set
            {
                OnKeywordMiscChanging(value);
                ReportPropertyChanging("KeywordMisc");
                _KeywordMisc = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("KeywordMisc");
                OnKeywordMiscChanged();
            }
        }
        private global::System.String _KeywordMisc;
        partial void OnKeywordMiscChanging(global::System.String value);
        partial void OnKeywordMiscChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AlarmWorkflowModel", "operationresource_ibfk_1", "operationresource")]
        public EntityCollection<OperationResourceData> OperationResources
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<OperationResourceData>("AlarmWorkflowModel.operationresource_ibfk_1", "operationresource");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<OperationResourceData>("AlarmWorkflowModel.operationresource_ibfk_1", "operationresource", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AlarmWorkflowModel", Name="OperationResourceData")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class OperationResourceData : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new OperationResourceData object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="operation_Id">Initial value of the Operation_Id property.</param>
        public static OperationResourceData CreateOperationResourceData(global::System.Int32 id, global::System.Int32 operation_Id)
        {
            OperationResourceData operationResourceData = new OperationResourceData();
            operationResourceData.Id = id;
            operationResourceData.Operation_Id = operation_Id;
            return operationResourceData;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Operation_Id
        {
            get
            {
                return _Operation_Id;
            }
            set
            {
                OnOperation_IdChanging(value);
                ReportPropertyChanging("Operation_Id");
                _Operation_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Operation_Id");
                OnOperation_IdChanged();
            }
        }
        private global::System.Int32 _Operation_Id;
        partial void OnOperation_IdChanging(global::System.Int32 value);
        partial void OnOperation_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Timestamp
        {
            get
            {
                return _Timestamp;
            }
            set
            {
                OnTimestampChanging(value);
                ReportPropertyChanging("Timestamp");
                _Timestamp = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Timestamp");
                OnTimestampChanged();
            }
        }
        private global::System.String _Timestamp;
        partial void OnTimestampChanging(global::System.String value);
        partial void OnTimestampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FullName
        {
            get
            {
                return _FullName;
            }
            set
            {
                OnFullNameChanging(value);
                ReportPropertyChanging("FullName");
                _FullName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FullName");
                OnFullNameChanged();
            }
        }
        private global::System.String _FullName;
        partial void OnFullNameChanging(global::System.String value);
        partial void OnFullNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EquipmentCsv
        {
            get
            {
                return _EquipmentCsv;
            }
            set
            {
                OnEquipmentCsvChanging(value);
                ReportPropertyChanging("EquipmentCsv");
                _EquipmentCsv = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EquipmentCsv");
                OnEquipmentCsvChanged();
            }
        }
        private global::System.String _EquipmentCsv;
        partial void OnEquipmentCsvChanging(global::System.String value);
        partial void OnEquipmentCsvChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AlarmWorkflowModel", "operationresource_ibfk_1", "OperationData")]
        public OperationData Operation
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<OperationData>("AlarmWorkflowModel.operationresource_ibfk_1", "OperationData").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<OperationData>("AlarmWorkflowModel.operationresource_ibfk_1", "OperationData").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<OperationData> OperationReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<OperationData>("AlarmWorkflowModel.operationresource_ibfk_1", "OperationData");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<OperationData>("AlarmWorkflowModel.operationresource_ibfk_1", "OperationData", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
