//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlarmWorkflow.Job.TelegramBotJob.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlarmWorkflow.Job.TelegramBotJob.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Api-Key darf nicht leer sein! ähnelt.
        /// </summary>
        internal static string ApiKeyEmptyWarningMessage {
            get {
                return ResourceManager.GetString("ApiKeyEmptyWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der TelegramBot hat einen Fehler erhalten. ähnelt.
        /// </summary>
        internal static string BotReceiveException {
            get {
                return ResourceManager.GetString("BotReceiveException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die registrierten Kontakte konnten nicht wiederhergestellt werden! ähnelt.
        /// </summary>
        internal static string ChatListInitializationErrorMessage {
            get {
                return ResourceManager.GetString("ChatListInitializationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dieser Befehl kann nur durch Admins benutzt werden um Benutzer zu aktivieren. ähnelt.
        /// </summary>
        internal static string ExportAcceptCommandDescription {
            get {
                return ResourceManager.GetString("ExportAcceptCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die /accept[chatId] ähnelt.
        /// </summary>
        internal static string ExportAcceptCommandDisplayName {
            get {
                return ResourceManager.GetString("ExportAcceptCommandDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die versendet Einsatz-Nachrichten über Telegram ähnelt.
        /// </summary>
        internal static string ExportJobDescription {
            get {
                return ResourceManager.GetString("ExportJobDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Telegram-Bot ähnelt.
        /// </summary>
        internal static string ExportJobDisplayName {
            get {
                return ResourceManager.GetString("ExportJobDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Diser Befehl ist zum anmelden am Bot mit dem angegeben Schlüssel ähnelt.
        /// </summary>
        internal static string ExportLoginCommandDescription {
            get {
                return ResourceManager.GetString("ExportLoginCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die /login [key] ähnelt.
        /// </summary>
        internal static string ExportLoginCommandDisplayName {
            get {
                return ResourceManager.GetString("ExportLoginCommandDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Befehl mit dem sich Benutzer abmelden können. ähnelt.
        /// </summary>
        internal static string ExportLogoutCommandDescription {
            get {
                return ResourceManager.GetString("ExportLogoutCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die /logout ähnelt.
        /// </summary>
        internal static string ExportLogoutCommandDisplayName {
            get {
                return ResourceManager.GetString("ExportLogoutCommandDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dieser Befehl kann nur durch Admins benutzt werden um Benutzer zu entfernen. ähnelt.
        /// </summary>
        internal static string ExportRemoveCommandDescription {
            get {
                return ResourceManager.GetString("ExportRemoveCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die /remove[chatId] ähnelt.
        /// </summary>
        internal static string ExportRemoveCommandDisplayName {
            get {
                return ResourceManager.GetString("ExportRemoveCommandDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Verarbeiten einer Nachricht einen Fehler veruracht. ähnelt.
        /// </summary>
        internal static string MessageHandlingFailed {
            get {
                return ResourceManager.GetString("MessageHandlingFailed", resourceCulture);
            }
        }
    }
}
