//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlarmWorkflow.Job.DisplayWakeUpJob.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlarmWorkflow.Job.DisplayWakeUpJob.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turning off display &apos;{0}&apos;....
        /// </summary>
        internal static string BeginTurnOffDisplayMessage {
            get {
                return ResourceManager.GetString("BeginTurnOffDisplayMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turning on display &apos;{0}&apos;....
        /// </summary>
        internal static string BeginTurnOnDisplayMessage {
            get {
                return ResourceManager.GetString("BeginTurnOnDisplayMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to the device for Uri &apos;{0}&apos;!.
        /// </summary>
        internal static string ConnectionToDeviceFailed {
            get {
                return ResourceManager.GetString("ConnectionToDeviceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to the device for Uri &apos;{0}&apos;, however the job is configured to ignore errors..
        /// </summary>
        internal static string ConnectionToDeviceFailedWithSuppression {
            get {
                return ResourceManager.GetString("ConnectionToDeviceFailedWithSuppression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schaltet Anzeigen ein und aus..
        /// </summary>
        internal static string ExportJobDescription {
            get {
                return ResourceManager.GetString("ExportJobDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Wake-Up.
        /// </summary>
        internal static string ExportJobDisplayName {
            get {
                return ResourceManager.GetString("ExportJobDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No display configurations have been found!.
        /// </summary>
        internal static string NoConfigurationsFoundError {
            get {
                return ResourceManager.GetString("NoConfigurationsFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing the URIs from line &apos;{0}&apos;. Skipping this line..
        /// </summary>
        internal static string ParseConfigFileUriFormatError {
            get {
                return ResourceManager.GetString("ParseConfigFileUriFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout of &apos;{0}&apos; reached for display &apos;{0}&apos;, initiating turn-off..
        /// </summary>
        internal static string PutDisplayIntoSleepMessage {
            get {
                return ResourceManager.GetString("PutDisplayIntoSleepMessage", resourceCulture);
            }
        }
    }
}
