//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34003
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlarmWorkflow.Job.Geocoding.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlarmWorkflow.Job.Geocoding.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verwendet den CloudMade Geocoding Dienst. ähnelt.
        /// </summary>
        internal static string ExportCloudMadeDescription {
            get {
                return ResourceManager.GetString("ExportCloudMadeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CloudeMade Geocoding ähnelt.
        /// </summary>
        internal static string ExportCloudMadeDisplayName {
            get {
                return ResourceManager.GetString("ExportCloudMadeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verwendet den Google Geocoding Dienst. ähnelt.
        /// </summary>
        internal static string ExportGoogleDescription {
            get {
                return ResourceManager.GetString("ExportGoogleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Google Geocoding ähnelt.
        /// </summary>
        internal static string ExportGoogleDisplayName {
            get {
                return ResourceManager.GetString("ExportGoogleDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Führt Geocoding Aufgaben aus. Wird für UI und Website benötigt! ähnelt.
        /// </summary>
        internal static string ExportJobDescription {
            get {
                return ResourceManager.GetString("ExportJobDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Geocoding ähnelt.
        /// </summary>
        internal static string ExportJobDisplayName {
            get {
                return ResourceManager.GetString("ExportJobDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verwendet den MapQuest Geocoding Dienst. ähnelt.
        /// </summary>
        internal static string ExportMapQuestDescription {
            get {
                return ResourceManager.GetString("ExportMapQuestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MapQuest Geocoding ähnelt.
        /// </summary>
        internal static string ExportMapQuestDisplayName {
            get {
                return ResourceManager.GetString("ExportMapQuestDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verwendet den OpenStreetMap Geocoding Dienst. ähnelt.
        /// </summary>
        internal static string ExportOpenStreetMapDescription {
            get {
                return ResourceManager.GetString("ExportOpenStreetMapDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OpenStreetMap Geocoding ähnelt.
        /// </summary>
        internal static string ExportOpenStreetMapDisplayName {
            get {
                return ResourceManager.GetString("ExportOpenStreetMapDisplayName", resourceCulture);
            }
        }
    }
}
