//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlarmWorkflow.Job.Geocoding.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlarmWorkflow.Job.Geocoding.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwendet den CloudMade Geocoding Dienst..
        /// </summary>
        internal static string ExportCloudMadeDescription {
            get {
                return ResourceManager.GetString("ExportCloudMadeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CloudMade Geocoding.
        /// </summary>
        internal static string ExportCloudMadeDisplayName {
            get {
                return ResourceManager.GetString("ExportCloudMadeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwendet den Google Geocoding Dienst..
        /// </summary>
        internal static string ExportGoogleDescription {
            get {
                return ResourceManager.GetString("ExportGoogleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Geocoding.
        /// </summary>
        internal static string ExportGoogleDisplayName {
            get {
                return ResourceManager.GetString("ExportGoogleDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Führt Geocoding Aufgaben aus. Wird für UI und Website benötigt!.
        /// </summary>
        internal static string ExportJobDescription {
            get {
                return ResourceManager.GetString("ExportJobDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geocoding.
        /// </summary>
        internal static string ExportJobDisplayName {
            get {
                return ResourceManager.GetString("ExportJobDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwendet den MapQuest Geocoding Dienst..
        /// </summary>
        internal static string ExportMapQuestDescription {
            get {
                return ResourceManager.GetString("ExportMapQuestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MapQuest Geocoding.
        /// </summary>
        internal static string ExportMapQuestDisplayName {
            get {
                return ResourceManager.GetString("ExportMapQuestDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwendet den OpenStreetMap Geocoding Dienst..
        /// </summary>
        internal static string ExportOpenStreetMapDescription {
            get {
                return ResourceManager.GetString("ExportOpenStreetMapDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenStreetMap Geocoding.
        /// </summary>
        internal static string ExportOpenStreetMapDisplayName {
            get {
                return ResourceManager.GetString("ExportOpenStreetMapDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The geocoding service has not returned any coordinates!.
        /// </summary>
        internal static string NoCoordinatesFoundByGeocodingService {
            get {
                return ResourceManager.GetString("NoCoordinatesFoundByGeocodingService", resourceCulture);
            }
        }
    }
}
