//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace AlarmWorkflow.BackendService.Dispositioning.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DispositioningEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DispositioningEntities object using the connection string found in the 'DispositioningEntities' section of the application configuration file.
        /// </summary>
        public DispositioningEntities() : base("name=DispositioningEntities", "DispositioningEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DispositioningEntities object.
        /// </summary>
        public DispositioningEntities(string connectionString) : base(connectionString, "DispositioningEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DispositioningEntities object.
        /// </summary>
        public DispositioningEntities(EntityConnection connection) : base(connection, "DispositioningEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DispResourceData> DispResources
        {
            get
            {
                if ((_DispResources == null))
                {
                    _DispResources = base.CreateObjectSet<DispResourceData>("DispResources");
                }
                return _DispResources;
            }
        }
        private ObjectSet<DispResourceData> _DispResources;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DispResources EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDispResources(DispResourceData dispResourceData)
        {
            base.AddObject("DispResources", dispResourceData);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DispositioningEntitiesModel", Name="DispResourceData")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DispResourceData : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DispResourceData object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="operation_Id">Initial value of the Operation_Id property.</param>
        /// <param name="timestamp">Initial value of the Timestamp property.</param>
        /// <param name="emkResourceId">Initial value of the EmkResourceId property.</param>
        public static DispResourceData CreateDispResourceData(global::System.Int32 id, global::System.Int32 operation_Id, global::System.DateTime timestamp, global::System.String emkResourceId)
        {
            DispResourceData dispResourceData = new DispResourceData();
            dispResourceData.Id = id;
            dispResourceData.Operation_Id = operation_Id;
            dispResourceData.Timestamp = timestamp;
            dispResourceData.EmkResourceId = emkResourceId;
            return dispResourceData;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Operation_Id
        {
            get
            {
                return _Operation_Id;
            }
            set
            {
                OnOperation_IdChanging(value);
                ReportPropertyChanging("Operation_Id");
                _Operation_Id = StructuralObject.SetValidValue(value, "Operation_Id");
                ReportPropertyChanged("Operation_Id");
                OnOperation_IdChanged();
            }
        }
        private global::System.Int32 _Operation_Id;
        partial void OnOperation_IdChanging(global::System.Int32 value);
        partial void OnOperation_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Timestamp
        {
            get
            {
                return _Timestamp;
            }
            set
            {
                OnTimestampChanging(value);
                ReportPropertyChanging("Timestamp");
                _Timestamp = StructuralObject.SetValidValue(value, "Timestamp");
                ReportPropertyChanged("Timestamp");
                OnTimestampChanged();
            }
        }
        private global::System.DateTime _Timestamp;
        partial void OnTimestampChanging(global::System.DateTime value);
        partial void OnTimestampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EmkResourceId
        {
            get
            {
                return _EmkResourceId;
            }
            set
            {
                OnEmkResourceIdChanging(value);
                ReportPropertyChanging("EmkResourceId");
                _EmkResourceId = StructuralObject.SetValidValue(value, false, "EmkResourceId");
                ReportPropertyChanged("EmkResourceId");
                OnEmkResourceIdChanged();
            }
        }
        private global::System.String _EmkResourceId;
        partial void OnEmkResourceIdChanging(global::System.String value);
        partial void OnEmkResourceIdChanged();

        #endregion

    }

    #endregion

}
