//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlarmWorkflow.Windows.Configuration.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlarmWorkflow.Windows.Configuration.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie müssen Administratorrechte besitzen, um diese Aktion auszuführen!.
        /// </summary>
        internal static string AdministratorRequiredMessage {
            get {
                return ResourceManager.GetString("AdministratorRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der endgültige Wert liegt außerhalb der erlaubten Grenzen von &apos;{0}&apos; - &apos;{1}&apos; (beide einschließlich) in der Einheit {2}..
        /// </summary>
        internal static string DurationTypeEditorOutsideBoundaries {
            get {
                return ResourceManager.GetString("DurationTypeEditorOutsideBoundaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konnte keine Verbindung zum Service herstellen! Stellen Sie sicher, dass die Verbindungsdaten korrekt sind und der Service auf dem Zielcomputer gestartet ist..
        /// </summary>
        internal static string EndpointNotFoundOnStart {
            get {
                return ResourceManager.GetString("EndpointNotFoundOnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; could not be found!.
        /// </summary>
        internal static string ExportEditorsTypeRequired {
            get {
                return ResourceManager.GetString("ExportEditorsTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konnte nicht zur URI {0} navigieren. Der Fehler war: {1}.
        /// </summary>
        internal static string HyperlinkRequestUriFailedMessage {
            get {
                return ResourceManager.GetString("HyperlinkRequestUriFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Wert muss zwischen &apos;{0}&apos; und &apos;{1}&apos; liegen..
        /// </summary>
        internal static string NumberTypeEditorValueNotValidHint {
            get {
                return ResourceManager.GetString("NumberTypeEditorValueNotValidHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Wert lag außerhalb des gültigen Wertebereichs..
        /// </summary>
        internal static string NumberTypeEditorValueNotValidMessage {
            get {
                return ResourceManager.GetString("NumberTypeEditorValueNotValidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema attributeFormDefault=&quot;unqualified&quot; elementFormDefault=&quot;qualified&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;xs:element name=&quot;Container&quot;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:sequence&gt;
        ///        &lt;xs:element name=&quot;Seed&quot;&gt;
        ///          &lt;xs:complexType&gt;
        ///            &lt;xs:sequence&gt;
        ///              &lt;xs:element maxOccurs=&quot;unbounded&quot; name=&quot;Set&quot;&gt;
        ///                &lt;xs:complexType&gt;
        ///                  &lt;xs:simpleContent&gt;
        ///                    &lt;xs:extension base=&quot;xs:string&quot;&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ObjectTestDatabaseSchema {
            get {
                return ResourceManager.GetString("ObjectTestDatabaseSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchten Sie den gewählten Eintrag wirklich löschen?.
        /// </summary>
        internal static string PrintingQueuesConfigurationWindowConfirmDeleteEntry {
            get {
                return ResourceManager.GetString("PrintingQueuesConfigurationWindowConfirmDeleteEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Änderungen übernehmen.
        /// </summary>
        internal static string PrintingQueuesConfigurationWindowLeaveConfirmation_CAP {
            get {
                return ResourceManager.GetString("PrintingQueuesConfigurationWindowLeaveConfirmation_CAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchten Sie die Änderungen übernehmen?
        ///
        ///Beachten Sie, dass Sie die Änderungen im Hauptfenster speichern müssen, damit es endgültig gespeichert wird..
        /// </summary>
        internal static string PrintingQueuesConfigurationWindowLeaveConfirmation_MSG {
            get {
                return ResourceManager.GetString("PrintingQueuesConfigurationWindowLeaveConfirmation_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Druckerwege-Konfiguration.
        /// </summary>
        internal static string PrintingQueuesConfigurationWindowTitle {
            get {
                return ResourceManager.GetString("PrintingQueuesConfigurationWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie sind im Begriff, den Service neuzustarten. Während dieser Zeit können keine Alarmquellen ausgewertet werden. Dieser Vorgang kann bis zu ein paar Minuten dauern. Bitte bestätigen Sie, dass Sie dies durchführen möchten..
        /// </summary>
        internal static string RestartServiceMessage {
            get {
                return ResourceManager.GetString("RestartServiceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungsgruppe {0} von {1} gespeichert..
        /// </summary>
        internal static string SaveSettingStatusText {
            get {
                return ResourceManager.GetString("SaveSettingStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Einstellungen wurden erfolgreich gespeichert!.
        /// </summary>
        internal static string SavingSettingsSuccess {
            get {
                return ResourceManager.GetString("SavingSettingsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Einstellungen wurden (mit Fehlern) gespeichert!.
        /// </summary>
        internal static string SavingSettingsWithErrors {
            get {
                return ResourceManager.GetString("SavingSettingsWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not validate the object test database file! Loading aborted..
        /// </summary>
        internal static string SeedEntryParseError {
            get {
                return ResourceManager.GetString("SeedEntryParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; not found on type &apos;{1}&apos;. Skipping..
        /// </summary>
        internal static string SeedEntryPropertyNotFound {
            get {
                return ResourceManager.GetString("SeedEntryPropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not set property &apos;{0}&apos; on type &apos;{1}&apos;. It will have its default value..
        /// </summary>
        internal static string SeedEntrySetPropertyFailed {
            get {
                return ResourceManager.GetString("SeedEntrySetPropertyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not format your input because of an internal error. Please see the log for further information!.
        /// </summary>
        internal static string SeedEntryTestFailed {
            get {
                return ResourceManager.GetString("SeedEntryTestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to cast the type &apos;{0}&apos; to IFormattable as instructed in the database file, but type is not IFormattable!.
        /// </summary>
        internal static string SeedEntryTestTypeIsNotIFormattable {
            get {
                return ResourceManager.GetString("SeedEntryTestTypeIsNotIFormattable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create an instance of the type &apos;{0}&apos; because it has no public default constructor defined!.
        /// </summary>
        internal static string SeedEntryTypeHasNoDefaultConstructor {
            get {
                return ResourceManager.GetString("SeedEntryTypeHasNoDefaultConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie sind dabei, den Service zu installieren. Bitte bestätigen Sie, um fortzufahren. Sie können dann anschließend den Service starten..
        /// </summary>
        internal static string ServiceInstallConfirmationMessage {
            get {
                return ResourceManager.GetString("ServiceInstallConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation des Services ist gescheitert. Die Fehlermeldung lautet: 
        ///
        ///&apos;{0}&apos;.
        /// </summary>
        internal static string ServiceInstallFailedMessage {
            get {
                return ResourceManager.GetString("ServiceInstallFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation des Services ist abgeschlossen! Sie können den Service nun starten..
        /// </summary>
        internal static string ServiceInstallSuccessMessage {
            get {
                return ResourceManager.GetString("ServiceInstallSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Service ist nicht installiert! Die Aktion kann nicht ausgeführt werden. Bitte installieren Sie zuerst den Service!.
        /// </summary>
        internal static string ServiceIsNotInstalledError {
            get {
                return ResourceManager.GetString("ServiceIsNotInstalledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Service konnte nicht gestartet werden. Die Fehlermeldung lautet:
        ///
        ///&apos;{0}&apos;.
        /// </summary>
        internal static string ServiceStartError {
            get {
                return ResourceManager.GetString("ServiceStartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Service konnte nicht gestoppt werden. Die Fehlermeldung lautet: 
        ///
        ///&apos;{0}&apos;.
        /// </summary>
        internal static string ServiceStopError {
            get {
                return ResourceManager.GetString("ServiceStopError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie sind dabei, den Service zu deinstallieren. Bitte bestätigen Sie, um fortzufahren..
        /// </summary>
        internal static string ServiceUninstallConfirmationMessage {
            get {
                return ResourceManager.GetString("ServiceUninstallConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Service läuft noch. Bitte beenden Sie ihn zuerst, bevor sie ihn deinstallieren!.
        /// </summary>
        internal static string ServiceUninstallErrorServiceIsRunningMessage {
            get {
                return ResourceManager.GetString("ServiceUninstallErrorServiceIsRunningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deinstallation des Services ist gescheitert. Die Fehlermeldung lautet: 
        ///
        ///&apos;{0}&apos;.
        /// </summary>
        internal static string ServiceUninstallFailedMessage {
            get {
                return ResourceManager.GetString("ServiceUninstallFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deinstallation des Services ist abgeschlossen!.
        /// </summary>
        internal static string ServiceUninstallSuccessMessage {
            get {
                return ResourceManager.GetString("ServiceUninstallSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while setting the user-value to settign &apos;{0}&apos;(Identifier &apos;{1}&apos;). Using the default value..
        /// </summary>
        internal static string SettingItemViewModelSetSettingError {
            get {
                return ResourceManager.GetString("SettingItemViewModelSetSettingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Einstellung &apos;{0}&apos; (in &apos;{1}&apos;) hat keine Anzeigekonfiguration und kann daher nicht angezeigt werden. Bitte beheben Sie das in der entsprechenden settings.info.xml..
        /// </summary>
        internal static string SettingNotFoundInDisplayConfiguration {
            get {
                return ResourceManager.GetString("SettingNotFoundInDisplayConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchten Sie den Wert dieser Einstellung zurücksetzen?.
        /// </summary>
        internal static string SettingResetConfirmation {
            get {
                return ResourceManager.GetString("SettingResetConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Fehler trat beim Speichern der Einstellung &apos;{0}&apos; (in &apos;{1}&apos;) auf. Wahrscheinlich ist der Wert für die Einstellung falsch, oder der Editor hat einen Fehler gemacht. Der neue Wert wurde nicht übernommen. Nachricht:
        ///
        ///{2}
        ///
        ///Hinweise zur Behebung:
        ///
        ///{3}.
        /// </summary>
        internal static string SettingSaveError {
            get {
                return ResourceManager.GetString("SettingSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Es gibt zu diesem Fehler keine gesonderten Hinweise).
        /// </summary>
        internal static string SettingSaveError_DefaultHints {
            get {
                return ResourceManager.GetString("SettingSaveError_DefaultHints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Speichern einer Einstellung.
        /// </summary>
        internal static string SettingSaveError_Title {
            get {
                return ResourceManager.GetString("SettingSaveError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen gespeichert.
        /// </summary>
        internal static string SettingSaveFinished_Title {
            get {
                return ResourceManager.GetString("SettingSaveFinished_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist ein Fehler während des Ladens der Einstellungen aufgetreten. Die Bearbeitung der Einstellung werden verhindert. Bitte sehen Sie in den Logs nach..
        /// </summary>
        internal static string SettingsInitializationError {
            get {
                return ResourceManager.GetString("SettingsInitializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A type editor with alias &apos;{0}&apos; was already registered. This new export is ignored. Please check assembly &apos;{1}&apos;..
        /// </summary>
        internal static string TypeEditorAlreadyRegisteredWarning {
            get {
                return ResourceManager.GetString("TypeEditorAlreadyRegisteredWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered type editor &apos;{0}&apos; with alias &apos;{1}&apos;..
        /// </summary>
        internal static string TypeEditorRegistered {
            get {
                return ResourceManager.GetString("TypeEditorRegistered", resourceCulture);
            }
        }
    }
}
