//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18034
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlarmWorkflow.Windows.Configuration.AddressBookEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlarmWorkflow.Windows.Configuration.AddressBookEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Änderungen übernehmen ähnelt.
        /// </summary>
        internal static string AddressBookWindowLeaveConfirmation_CAP {
            get {
                return ResourceManager.GetString("AddressBookWindowLeaveConfirmation_CAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Möchten Sie die Änderungen übernehmen?
        ///
        ///Beachten Sie, dass Sie die Änderungen im Hauptfenster speichern müssen, damit es endgültig gespeichert wird. ähnelt.
        /// </summary>
        internal static string AddressBookWindowLeaveConfirmation_MSG {
            get {
                return ResourceManager.GetString("AddressBookWindowLeaveConfirmation_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Adressbuch-Editor ähnelt.
        /// </summary>
        internal static string AddressBookWindowTitle {
            get {
                return ResourceManager.GetString("AddressBookWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Möchten Sie den gewählten Eintrag wirklich löschen? ähnelt.
        /// </summary>
        internal static string ConfirmDeleteEntry {
            get {
                return ResourceManager.GetString("ConfirmDeleteEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error occurred while loading the data item value from item with identifier &apos;{0}&apos;. See log for further information. ähnelt.
        /// </summary>
        internal static string ErrorWhileLoadingDataItemValue {
            get {
                return ResourceManager.GetString("ErrorWhileLoadingDataItemValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schleifencode ähnelt.
        /// </summary>
        internal static string INF_LoopCustomDataEditor {
            get {
                return ResourceManager.GetString("INF_LoopCustomDataEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die E-Mail Adresse ähnelt.
        /// </summary>
        internal static string INF_MailCustomDataEditor {
            get {
                return ResourceManager.GetString("INF_MailCustomDataEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Telefonnummer ähnelt.
        /// </summary>
        internal static string INF_MobilePhoneCustomDataEditor {
            get {
                return ResourceManager.GetString("INF_MobilePhoneCustomDataEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Push-Empfänger ähnelt.
        /// </summary>
        internal static string INF_PushCustomDataEditor {
            get {
                return ResourceManager.GetString("INF_PushCustomDataEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die angegebene Adresse ist ungültig. ähnelt.
        /// </summary>
        internal static string VR_Mail_InvalidAddress {
            get {
                return ResourceManager.GetString("VR_Mail_InvalidAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kein Wert! ähnelt.
        /// </summary>
        internal static string VR_NoValue {
            get {
                return ResourceManager.GetString("VR_NoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ungültiges Nummernformat! Aus Rücksichtnahme auf verschiedenste Dienste benutzen Sie bitte nur Zahlen, ohne Leerzeichen, Klammern etc. ähnelt.
        /// </summary>
        internal static string VR_Phone_InvalidNumber {
            get {
                return ResourceManager.GetString("VR_Phone_InvalidNumber", resourceCulture);
            }
        }
    }
}
