//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlarmWorkflow.Windows.Configuration.AddressBookEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlarmWorkflow.Windows.Configuration.AddressBookEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Änderungen übernehmen.
        /// </summary>
        internal static string AddressBookWindowLeaveConfirmation_CAP {
            get {
                return ResourceManager.GetString("AddressBookWindowLeaveConfirmation_CAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchten Sie die Änderungen übernehmen?.
        /// </summary>
        internal static string AddressBookWindowLeaveConfirmation_MSG {
            get {
                return ResourceManager.GetString("AddressBookWindowLeaveConfirmation_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adressbuch-Editor.
        /// </summary>
        internal static string AddressBookWindowTitle {
            get {
                return ResourceManager.GetString("AddressBookWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchten Sie den gewählten Eintrag wirklich löschen?.
        /// </summary>
        internal static string ConfirmDeleteEntry {
            get {
                return ResourceManager.GetString("ConfirmDeleteEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading the data item value from item with identifier &apos;{0}&apos;. See log for further information..
        /// </summary>
        internal static string ErrorWhileLoadingDataItemValue {
            get {
                return ResourceManager.GetString("ErrorWhileLoadingDataItemValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schleifencode.
        /// </summary>
        internal static string INF_LoopCustomDataEditor {
            get {
                return ResourceManager.GetString("INF_LoopCustomDataEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail Adresse.
        /// </summary>
        internal static string INF_MailCustomDataEditor {
            get {
                return ResourceManager.GetString("INF_MailCustomDataEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefonnummer.
        /// </summary>
        internal static string INF_MobilePhoneCustomDataEditor {
            get {
                return ResourceManager.GetString("INF_MobilePhoneCustomDataEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die angegebene Adresse ist ungültig..
        /// </summary>
        internal static string VR_Mail_InvalidAddress {
            get {
                return ResourceManager.GetString("VR_Mail_InvalidAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kein Wert!.
        /// </summary>
        internal static string VR_NoValue {
            get {
                return ResourceManager.GetString("VR_NoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültiges Nummernformat! Aus Rücksichtnahme auf verschiedenste Dienste benutzen Sie bitte nur Zahlen, ohne Leerzeichen, Klammern etc..
        /// </summary>
        internal static string VR_Phone_InvalidNumber {
            get {
                return ResourceManager.GetString("VR_Phone_InvalidNumber", resourceCulture);
            }
        }
    }
}
