//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlarmWorkflow.Parser.GenericParser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlarmWorkflow.Parser.GenericParser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbenannter Bereich.
        /// </summary>
        internal static string AreaBlankName {
            get {
                return ResourceManager.GetString("AreaBlankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Abschnitt, dessen Inhalte als Kommentare/Bemerkungen betrachtet werden (i.d.R. ein Fließtext über mehrere Zeilen)..
        /// </summary>
        internal static string CommentSectionParser_Description {
            get {
                return ResourceManager.GetString("CommentSectionParser_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kommentarabschnitt.
        /// </summary>
        internal static string CommentSectionParser_DisplayName {
            get {
                return ResourceManager.GetString("CommentSectionParser_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steuerungsdateien (*.xml)|*.xml.
        /// </summary>
        internal static string Controlfile_FilterText {
            get {
                return ResourceManager.GetString("Controlfile_FilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The generic parser is still in Beta-stadium! Please communicate any bugs or anomalies to the developers. Thank you!.
        /// </summary>
        internal static string GenericParserBetaWarningText {
            get {
                return ResourceManager.GetString("GenericParserBetaWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Abschnitt, der Schlagwörter (z. B. &quot;B&quot;, &quot;T&quot; etc.) enthält..
        /// </summary>
        internal static string KeywordSectionParser_Description {
            get {
                return ResourceManager.GetString("KeywordSectionParser_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schlagwörterabschnitt.
        /// </summary>
        internal static string KeywordSectionParser_DisplayName {
            get {
                return ResourceManager.GetString("KeywordSectionParser_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Keine Beschreibung verfügbar).
        /// </summary>
        internal static string NoDescriptionAvailableText {
            get {
                return ResourceManager.GetString("NoDescriptionAvailableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Abschnitt, der die Einsatznummer enthält..
        /// </summary>
        internal static string OperationNumberSectionParser_Description {
            get {
                return ResourceManager.GetString("OperationNumberSectionParser_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einsatznummerabschnitt.
        /// </summary>
        internal static string OperationNumberSectionParser_DisplayName {
            get {
                return ResourceManager.GetString("OperationNumberSectionParser_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbenannter Parser.
        /// </summary>
        internal static string ParserDefinitionBlankName {
            get {
                return ResourceManager.GetString("ParserDefinitionBlankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Abschnitt, der Ortsinformationen (z. B. &quot;Einsatzort&quot;, &quot;Zielort&quot;) enthält..
        /// </summary>
        internal static string PropertyLocationSectionParser_Description {
            get {
                return ResourceManager.GetString("PropertyLocationSectionParser_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ortsinformationsabschnitt.
        /// </summary>
        internal static string PropertyLocationSectionParser_DisplayName {
            get {
                return ResourceManager.GetString("PropertyLocationSectionParser_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Abschnitt, der eine Auflistung der Einsatzmittel darstellt..
        /// </summary>
        internal static string ResourcesSectionParser_Description {
            get {
                return ResourceManager.GetString("ResourcesSectionParser_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einsatzmittelabschnitt.
        /// </summary>
        internal static string ResourcesSectionParser_DisplayName {
            get {
                return ResourceManager.GetString("ResourcesSectionParser_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbenannter Abschnitt.
        /// </summary>
        internal static string SectionBlankName {
            get {
                return ResourceManager.GetString("SectionBlankName", resourceCulture);
            }
        }
    }
}
