//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlarmWorkflow.Windows.Configuration.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlarmWorkflow.Windows.Configuration.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Einstellungen wurden erfolgreich gespeichert!.
        /// </summary>
        internal static string SavingSettingsSuccess {
            get {
                return ResourceManager.GetString("SavingSettingsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Einstellungen wurden (mit Fehlern) gespeichert!.
        /// </summary>
        internal static string SavingSettingsWithErrors {
            get {
                return ResourceManager.GetString("SavingSettingsWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while setting the user-value to settign &apos;{0}&apos;(Identifier &apos;{1}&apos;). Using the default value..
        /// </summary>
        internal static string SettingItemViewModelSetSettingError {
            get {
                return ResourceManager.GetString("SettingItemViewModelSetSettingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Einstellung &apos;{0}&apos; (in &apos;{1}&apos;) hat keine Anzeigekonfiguration und kann daher nicht angezeigt werden. Bitte beheben Sie das in der entsprechenden settings.info.xml..
        /// </summary>
        internal static string SettingNotFoundInDisplayConfiguration {
            get {
                return ResourceManager.GetString("SettingNotFoundInDisplayConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchten Sie den Wert dieser Einstellung zurücksetzen?.
        /// </summary>
        internal static string SettingResetConfirmation {
            get {
                return ResourceManager.GetString("SettingResetConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Fehler trat beim Speichern der Einstellung &apos;{0}&apos; (in &apos;{1}&apos;) auf. Wahrscheinlich ist der Wert für die Einstellung falsch, oder der Editor hat einen Fehler gemacht. Der neue Wert wurde nicht übernommen. Nachricht:.
        /// </summary>
        internal static string SettingSaveError {
            get {
                return ResourceManager.GetString("SettingSaveError", resourceCulture);
            }
        }
    }
}
